// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ContenteditableJs = require("./contenteditable.js");

function make(html, autofocus, className, onChange, onKeyUp, onKeyDown, onBlur, onFocus, children) {
  return ReasonReact.wrapJsForReason(ContenteditableJs, {
              html: html,
              autofocus: autofocus,
              className: className,
              onKeyUp: onKeyUp,
              onKeyDown: onKeyDown,
              onBlur: onBlur,
              onChange: onChange,
              onFocus: onFocus
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
