// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var SExp$ReactTemplate = require("./SExp.bs.js");
var Terminal$ReactTemplate = require("./Terminal.bs.js");
var SExpEditor$ReactTemplate = require("./SExpEditor.bs.js");

var expr = SExp$ReactTemplate.parse("(module test (define (quote main) (println (string (Hello, () world)))))");

var component = ReasonReact.reducerComponent("SyncView");

function make(data, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              return React.createElement("div", {
                          className: "SyncView"
                        }, ReasonReact.element(/* None */0, /* None */0, SExpEditor$ReactTemplate.make(self[/* state */1][/* exp */0], (function (x) {
                                    return Curry._1(self[/* send */3], /* Update */[x]);
                                  }), /* array */[])), React.createElement("pre", undefined, SExp$ReactTemplate.toString(self[/* state */1][/* exp */0])));
            }),
          /* initialState */(function () {
              return /* record */[/* exp */data];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (param, _) {
              return /* Update */Block.__(0, [/* record */[/* exp */param[0]]]);
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var SyncView = /* module */[
  /* component */component,
  /* make */make
];

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Terminal$ReactTemplate.make(/* array */[])), "app");

exports.expr = expr;
exports.SyncView = SyncView;
/* expr Not a pure module */
